name: ❓ Question
description: Confused? So are we sometimes. Let's figure it out.
title: "[QUESTION] "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        This project ain't your everyday messaging app. Ask your questions here.

  - type: textarea
    id: question
    attributes:
      label: What's confusing you?
      description: Don't be shy. Hit us with it.
      placeholder: I don't get how clients talk to each other without a server...
    validations:
      required: true
